// SPDX-FileCopyrightText: GARDENA GmbH
//
// SPDX-License-Identifier: GPL-3.0-or-later

use crate::dbus_helper::ConnectionFailed;
use crate::dbus_helper::Network;
use crate::dbus_helper::WpaDbusHelper;
use crate::wifiapi;
use anyhow::{bail, Result};
use axum::http::StatusCode;
use axum::{extract, Json};
use serde::{Deserialize, Serialize};
use std::convert::TryInto;
use std::time::Duration;
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};
use tokio::time::timeout;
use tracing::{error, info};

const WIFI_NETWORK_INTERFACE: &str = "wlan0";

#[derive(PartialEq, Debug, Deserialize, Serialize)]
pub enum KeyMgmt {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "WPA-PSK")]
    Wpapsk,
}

#[derive(PartialEq, Debug, Deserialize, Serialize)]
pub struct Config {
    pub ssid: String,
    pub key_mgmt: KeyMgmt,
    pub psk: String,
}

pub struct WiFiApi<T> {
    inner: T,
}

async fn new() -> Result<WiFiApi<impl AsyncRead + AsyncWrite>> {
    Ok(WiFiApi {
        inner: tokio::net::UnixStream::connect("/var/run/accessoryserver_wifiapi").await?,
    })
}

impl<T> WiFiApi<T>
where
    T: AsyncRead + AsyncWrite + Unpin,
{
    async fn read_byte(&mut self) -> Result<u8> {
        let mut buf = [0x00; 1];
        self.inner.read_exact(&mut buf).await?;
        Ok(buf[0])
    }

    async fn write_byte(&mut self, byte: u8) -> Result<()> {
        let buf = [byte; 1];
        Ok(self.inner.write_all(&buf).await?)
    }

    async fn read_res(&mut self) -> Result<()> {
        let res = self.read_byte().await?;
        if res != 0x00 {
            bail!("accessory-server command failed with error code: {}", res);
        }

        Ok(())
    }

    async fn run_cmd(&mut self, cmd: u8) -> Result<()> {
        self.write_byte(cmd).await?;
        self.read_res().await
    }

    pub async fn hap_clear_pairings(&mut self) -> Result<()> {
        // Originally generated by rust-bindgen from `accessoryserver/wifiapi_public.h`.
        static CMD_HAP_CLEAR_PAIRINGS: ::std::os::raw::c_uint = 5;

        self.run_cmd(CMD_HAP_CLEAR_PAIRINGS.try_into()?).await?;
        Ok(())
    }
}

async fn new_wpa_dbus_helper() -> Result<WpaDbusHelper, StatusCode> {
    let wifis_dbus = WpaDbusHelper::new_with_system_bus(WIFI_NETWORK_INTERFACE)
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(wifis_dbus)
}

pub async fn get_wifi_settings() -> Result<Json<Option<Config>>, StatusCode> {
    let wifis_dbus = new_wpa_dbus_helper().await?;

    let config = wifis_dbus
        .get_configured_ssid()
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    // The PSK is never sent to the client.
    debug_assert!(config.as_ref().map_or(true, |c| c.psk.is_empty()));

    Ok(Json(config))
}

/// The upper bound for a whole configuration request.
///
/// The request waits for the connection to be established, so a configuration
/// the gateway cannot connect with is rolled back instead of leaving the
/// gateway unreachable. `WpaDbusHelper::configure` stops waiting slightly
/// earlier than this, so it still has time to roll back and report the failure.
const SET_WIFI_TIMEOUT: Duration = Duration::from_secs(45);

/// Applies a Wi-Fi configuration.
///
/// This blocks until the gateway is connected to the given network, or until the
/// attempt has failed and been rolled back.
///
/// * `400 Bad Request`: the configuration is invalid (SSID or key not usable).
/// * `422 Unprocessable Entity`: the configuration is valid, but the gateway
///   could not connect to that network.
/// * `408 Request Timeout`: the attempt did not finish in time.
/// * `500 Internal Server Error`: talking to wpa_supplicant failed.
pub async fn set_wifi_settings(
    extract::Json(settings): extract::Json<Config>,
) -> Result<StatusCode, StatusCode> {
    // Validate before touching D-Bus: an invalid configuration must be rejected
    // immediately instead of costing a connection attempt and its timeout.
    validate_config(&settings).map_err(|_| StatusCode::BAD_REQUEST)?;

    let wifis_dbus = new_wpa_dbus_helper().await?;

    timeout(SET_WIFI_TIMEOUT, wifis_dbus.configure(&settings))
        .await
        .map_err(|_| {
            error!("Applying the Wi-Fi configuration timed out");
            StatusCode::REQUEST_TIMEOUT
        })?
        .map_err(|e| {
            // The configuration itself was acceptable, so a failure to associate
            // is reported separately from an internal (D-Bus) failure.
            if e.downcast_ref::<ConnectionFailed>().is_some() {
                info!(
                    "Could not connect with the given Wi-Fi configuration: {}",
                    e
                );
                StatusCode::UNPROCESSABLE_ENTITY
            } else {
                error!("Failed to configure Wi-Fi: {}", e);
                StatusCode::INTERNAL_SERVER_ERROR
            }
        })?;

    Ok(StatusCode::NO_CONTENT)
}

fn validate_config(config: &Config) -> Result<()> {
    check_ssid_length(&config.ssid)?;

    // An open network is configured without a key, whatever the client sent.
    if config.key_mgmt == KeyMgmt::Wpapsk {
        check_psk(&config.psk)?;
    }

    Ok(())
}

/// The SSID is at most 32 octets long (not NULL-terminated) and not empty.
fn check_ssid_length(ssid: &str) -> Result<()> {
    if ssid.is_empty() {
        bail!("SSID is empty");
    }
    if ssid.len() > 32 {
        bail!("SSID length is too long: {}", ssid.len());
    }
    Ok(())
}

/// A WPA-PSK credential is either an 8 to 63 character passphrase or the
/// pre-shared key itself as 64 hexadecimal digits (IEEE 802.11i).
fn check_psk(psk: &str) -> Result<()> {
    if psk.is_empty() {
        bail!("PSK missing for encrypted network");
    }

    if psk.len() == 64 {
        if !psk.chars().all(|c| c.is_ascii_hexdigit()) {
            bail!("64 character PSK is not a valid hexadecimal key");
        }
    } else if psk.len() < 8 || psk.len() > 63 {
        bail!("PSK length out of range: {}", psk.len());
    }

    Ok(())
}

pub async fn delete_wifi_settings() -> Result<StatusCode, StatusCode> {
    let wifis_dbus = new_wpa_dbus_helper().await?;

    wifis_dbus
        .deactivate_wifi()
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    Ok(StatusCode::NO_CONTENT)
}

/// Lists the available Wi-Fi networks, strongest first.
///
/// A failing scan is an error rather than an empty list: the client shows the
/// user an empty selection otherwise, without any hint that scanning failed.
pub async fn get_wifi_list() -> Result<Json<Vec<Network>>, StatusCode> {
    let wifis_dbus = new_wpa_dbus_helper().await?;
    // The list is already deduplicated and ordered by signal strength.
    let wifis = wifis_dbus.scan().await.map_err(|e| {
        error!("Failed to scan for Wi-Fi networks: {}", e);
        StatusCode::INTERNAL_SERVER_ERROR
    })?;

    Ok(Json(wifis))
}

pub async fn delete_homekit_pairings() -> Result<StatusCode, StatusCode> {
    wifiapi::new()
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?
        .hap_clear_pairings()
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;

    Ok(StatusCode::NO_CONTENT)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_check_ssid_length_ok() {
        let valid_ssid = "A".repeat(32);
        assert!(check_ssid_length(&valid_ssid).is_ok());
    }
    #[tokio::test]
    async fn test_check_ssid_length_too_long() {
        let long_ssid = "A".repeat(33);
        assert_eq!(long_ssid.len(), 33);
        assert!(check_ssid_length(&long_ssid).is_err());
    }

    #[tokio::test]
    async fn test_check_ssid_length_too_long_unicode() {
        let long_ssid = "éléphant français 🐘 est vert".to_string();

        assert_eq!(long_ssid.chars().count(), 28);
        assert_eq!(long_ssid.len(), 34);
        assert!(check_ssid_length(&long_ssid).is_err());
    }

    #[test]
    fn test_check_ssid_empty() {
        assert!(check_ssid_length("").is_err());
    }

    #[test]
    fn test_check_psk_passphrase() {
        assert!(check_psk("12345678").is_ok());
        assert!(check_psk(&"A".repeat(63)).is_ok());
    }

    #[test]
    fn test_check_psk_rejects_empty_and_out_of_range() {
        assert!(check_psk("").is_err());
        assert!(check_psk("1234567").is_err());
        assert!(check_psk(&"A".repeat(65)).is_err());
    }

    #[test]
    fn test_check_psk_hex_key() {
        // 64 characters are only allowed as the raw hexadecimal key
        assert!(check_psk(&"a1B2".repeat(16)).is_ok());
        assert!(check_psk(&"Z".repeat(64)).is_err());
    }

    fn config(ssid: &str, key_mgmt: KeyMgmt, psk: &str) -> Config {
        Config {
            ssid: ssid.to_string(),
            key_mgmt,
            psk: psk.to_string(),
        }
    }

    #[test]
    fn test_validate_config_ok() {
        assert!(validate_config(&config("net", KeyMgmt::Wpapsk, "supersecret")).is_ok());
        assert!(validate_config(&config("net", KeyMgmt::None, "")).is_ok());
    }

    #[test]
    fn test_validate_config_rejects_missing_psk() {
        assert!(validate_config(&config("net", KeyMgmt::Wpapsk, "")).is_err());
    }

    #[test]
    fn test_validate_config_ignores_psk_for_open_network() {
        assert!(validate_config(&config("net", KeyMgmt::None, "short")).is_ok());
    }
}
